name: Release packages

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup pnpm for all the virtual machine
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup a especific node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run publish-packages
          version: pnpm run version-packages
        env:
          # Changesets needs a GitHub token to be able to create a release pull request
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # If you want to publish to npm, you need to set up an npm token, so changesets can publish your packages
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
